version: '3'

services:

  backends:
    # images:
    container_name: node-express
    build:
      context: ./backend/ #สั่งให้ build ตัว dockerfile อยู่ใน directory ต่ำกว่านี้ คือ backend เพราะว่าเรา
      
    # ต้อง map port ด้วย แค่ EXPOSE ไม่พอ 
    ports:
      - 3000:3000
    restart: on-failure
    links:
      - mongodb
    
      
    networks:
      - back_end
    
  mongodb:
    container_name: mongodb
    # image: mongo
    build: ./db
    # ports: 
    #   - 27017:27017
      # - 29000:29000
    volumes: 
      # - db-data:/usr/src/app #name:directory # Named Volume
      # - ./data/db:/data/db # bind mount ???
      # - db-data:/usr/src/app
      - db-data:/tmp
    
    networks:
      - back_end

volumes: 
  db-data:


networks:
  back_end: