FROM node:latest

WORKDIR /usr/src/app

COPY package.json package-lock.json /usr/src/app/

# RUN npm install -g npm@7.14.0
RUN npm install -g --unsafe-perm node-sass

RUN npm install

COPY ./src/server.js .

EXPOSE 3000

CMD [ "node", "server.js" ]